######################################################################
# Automatically generated by qmake (3.0) Sat Apr 4 17:13:59 2015
######################################################################

TEMPLATE = app
TARGET = demoMod

DEFINES += __STK_REALTIME__ LITTLE_ENDIAN __OS_LINUX__

HEADERS += utilities.h

SOURCES += demo.cpp \
	    utilities.cpp

LIBS += -lstk -lrtaudio
